# pyproject.toml
[tool.pytest.ini_options]
testpaths = [
    "tests",
    "integration",
]
asyncio_default_fixture_loop_scope = "function"
filterwarnings = [
    'ignore:configuration option "asyncio_default_fixture_loop_scope" is unset',
]